### ISSUE TITLE
Loose boto3 dependency 

### ISSUE THREAD

**Issue by elmago** [terrycain/aioboto3#277]
* Async AWS SDK for Python version: 10.1.0
* Python version: 3.9
* Operating System: MacOs

### Description

I'm having dependency conflicts when I try to setup **aioboto3** v10.1.0 because my project already has a **boto3** v1.24.80 dependency. Unluckily **aioboto3** v10.1.0 requires **boto3** <1.24.60 but I can't just downgrade boto3. 

### What I Did

I can't do more than waiting for the next **aioboto** version hoping that **boto3** internal dependency had been loosen.

**Comment by terrycain** [comment]
So the `boto3` dependency comes from `aiobotocore`, and the hard dependency on `aiobotocore` is due to the fact we both use and patch methods of `boto3` therefore if `boto3` was allowed to update/downgrade we'd be patching and consuming code that might not work.

Its annoying I get but theres nothing much we can do until `botocore` itself becomes async compatible. I'd suggest if you can not having a dependency on boto3 itself (assumings it not a dependency of something else)
